###
GET http://localhost:5000/canciones

###

POST http://localhost:5000/canciones
Content-Type: application/json

{
  "id": 1,
  "titulo": "Canción 1",
  "artista": "Artista 1",
  "tono": "C#m"
}

###

PUT http://localhost:5000/canciones/1
Content-Type: application/json

{
  "titulo": "Canción 1 (Actualizada)"
}

###

DELETE http://localhost:5000/canciones/1
